In [15]:
import numpy as np

In [18]:
arr_2d= np.array([[[3,2,1],[5,0,15]],[[5,6,10],[66,12,5]]])

In [19]:
arr_2d

array([[[ 3,  2,  1],
        [ 5,  0, 15]],

       [[ 5,  6, 10],
        [66, 12,  5]]])

In [3]:
arr = np.arange(0,11)

In [22]:
np.array([range(i,i+4) for i in (1,2,3)])

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [23]:
np.ones((2,4),dtype=float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
np.full((3,5),7.8)

array([[7.8, 7.8, 7.8, 7.8, 7.8],
       [7.8, 7.8, 7.8, 7.8, 7.8],
       [7.8, 7.8, 7.8, 7.8, 7.8]])

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [5]:
arr[8]

8

In [6]:
arr[1:4]

array([1, 2, 3])

In [7]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [9]:
arr[6:]

array([ 6,  7,  8,  9, 10])

In [10]:
arr[0:5] =100

In [11]:
arr= np.arange(0,11)

In [12]:
slice_of_arr= arr[0:6]

In [13]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [14]:
slice_of_arr[:] =99

In [15]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [16]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [17]:
arr_copy=arr.copy()

In [18]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [19]:
arr_2d= np.array([[5,0,15],[1,6,10],[66,12,5]])

In [20]:
arr_2d

array([[ 5,  0, 15],
       [ 1,  6, 10],
       [66, 12,  5]])

In [21]:
arr_2d[1,2]

10

In [22]:
arr_2d[1][0]

1

In [23]:
arr_2d[2:]

array([[66, 12,  5]])

In [26]:
arr=np.arange(1,11)

In [27]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
bool_arr= arr>5

In [37]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [38]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [39]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [40]:
arr_2d=np.arange(50).reshape(5,10)

In [41]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [46]:
arr_2d[0:4,4:5]

array([[ 4],
       [14],
       [24],
       [34]])